-- MySQL Script generated by MySQL Workbench
-- Thu Dec  3 17:34:35 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema qualitysystem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema qualitysystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `qualitysystem` DEFAULT CHARACTER SET utf8 ;
USE `qualitysystem` ;

-- -----------------------------------------------------
-- Table `qualitysystem`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qualitysystem`.`departments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qualitysystem`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qualitysystem`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qualitysystem`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qualitysystem`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `login` VARCHAR(50) NOT NULL,
  `password` VARCHAR(120) NOT NULL,
  `email` VARCHAR(75) NOT NULL,
  `department_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_departments1_idx` (`department_id` ASC) VISIBLE,
  INDEX `fk_users_roles2_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_departments1`
    FOREIGN KEY (`department_id`)
    REFERENCES `qualitysystem`.`departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_roles2`
    FOREIGN KEY (`role_id`)
    REFERENCES `qualitysystem`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qualitysystem`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qualitysystem`.`customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(40) NOT NULL,
  `address` VARCHAR(60) NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `fax` VARCHAR(20) NULL,
  `email` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qualitysystem`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qualitysystem`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `order_date` DATE NOT NULL,
  `shipped_date` DATE NOT NULL,
  `notes` VARCHAR(300) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_customer1_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `qualitysystem`.`customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qualitysystem`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qualitysystem`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `decimal_number` VARCHAR(30) NOT NULL,
  `amount` INT NOT NULL,
  `priority` VARCHAR(1) NOT NULL,
  `model_link` VARCHAR(200) NULL,
  `model_icon` BLOB NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_list_order_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_list_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `qualitysystem`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qualitysystem`.`processes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qualitysystem`.`processes` (
  `id` INT NOT NULL,
  `name` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qualitysystem`.`route_map`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qualitysystem`.`route_map` (
  `products_id` INT NOT NULL,
  `queue` INT NOT NULL,
  `processes_id` INT NOT NULL,
  `users_id` INT NULL,
  `start_time` TIMESTAMP(14) NULL,
  `comment` VARCHAR(200) NULL,
  INDEX `fk_route_map_products1_idx` (`products_id` ASC) VISIBLE,
  INDEX `fk_route_map_processes1_idx` (`processes_id` ASC) VISIBLE,
  INDEX `fk_route_map_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_route_map_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `qualitysystem`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_route_map_processes1`
    FOREIGN KEY (`processes_id`)
    REFERENCES `qualitysystem`.`processes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_route_map_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `qualitysystem`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
